name: Release

on:
  release:
    types: 
        - created

jobs:
  build:
    name: Build cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
            platforms: 'linux/amd64, darwin/amd64, windows/amd64, linux/arm64, darwin/arm64, windows/arm64'
            name: 'mhmods'
            compress: 'true'
            dest: 'build'
      
      - name: Upload build artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "./build/*.tar.gz"
