name: Release Builds

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.22]
        os: [linux, windows, darwin]
        arch: [amd64, arm64]
        include:
          - os: windows
            extension: .exe
          - os: linux
            extension: ''
          - os: darwin
            extension: ''

    name: Build for ${{ matrix.os }}/${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          go build -o mhmods-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.extension }}

      - name: Compress binary
        run: |
          tar -czvf mhmods-${{ matrix.os }}-${{ matrix.arch }}.tar.gz mhmods-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.extension }} ${LICENSE:+"LICENSE"} ${README:+"README.md"}
        env:
          LICENSE: ${{ github.workspace }}/LICENSE
          README: ${{ github.workspace }}/README.md

      - uses: actions/upload-artifact@v3
        with:
          name: mhmods-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
          path: mhmods-${{ matrix.os }}-${{ matrix.arch }}.tar.gz

      - uses: actions/download-artifact@v3
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: mhmods-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
          asset_name: mhmods-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
          asset_content_type: application/gzip
